version: '3.8'

services: 
    web:
        image: nginx
        ports: 
            - '8080:80'
        volumes: 
            - .:/usr/share/nginx/html

    db:
        image: mysql:8
        ports: 
            - '3306:3306'

    jar:
        build: .
        ports:
            -'5001:80'
        environment: 
            - DATABASE:jdbc:localhost:3306

